name: CD

on:
  push:
    branches: [ main ]

jobs:
  build: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
            node-version: 20
      - run: npm ci
      - run: npm run build
      
